### ISSUE TITLE
Cannot insert breakpoint, Cannot access memory at address XXX

### ISSUE THREAD

**Issue by konradsa** [WebFreak001/code-debug#301] opened 2021-11-17 17:09 UTC
- [x] If you are using gdb
  - [x] `gdb --version` >= 7.7.1
  - [x] it works on the command line with `gdb`
  - [x] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

When trying to debug a binary under Linux (using remote ssh from windows), I get the following error when trying to set a breakpoint once the task is running:

`Cannot insert breakpoint, Cannot access memory at address XXX`

Setting breakpoints works fine when application is not running yet, but as soon as I launch the application I cannot set a breakpoint without getting the error above.

No such issues with plain gdb or using the debug support from the vscode C++ extension.

Any idea how to fix this? I searched for similar issues, but was not able to find anything. This can't be a generic problem, since otherwise more people would complain about something like that. I read about this being related to Position Independent Code, but plain GDB and the Microsoft extension work just fine, so not sure what the issue is.

**Comment by brownts** [comment] 2021-11-18 00:58
Is the task paused when you attempt to set the breakpoint?  You indicated that this occurs after the task is running, but it was unclear if you pause execution after it had been running prior to attempting to set the breakpoint.  I'm assuming that you probably didn't pause the execution.  I believe there is a known issue where you can't set breakpoints while running, as described in #250.  The error message described there however seems different than the message described above.

You can enable additional debug information and provide that here as well, by setting "printCalls" and "showDevDebugOutput" to "true" in your launch.json for the task and then capturing the additional output.  That could provide more information about what is happening under the hood.

**Comment by konradsa** [comment] 2021-11-22 21:27
You are correct, it appears to be a problem only when the task is running, it works okay when the task is paused.

**Comment by GitMensch** [comment] 2022-04-24 13:25
Closed as effectively a duplicate of #250 (which of course still needs to be taken care of somedayTM).

**Closed by GitMensch** 2022-04-24 13:25 UTC
