### ISSUE TITLE
Not support multithreading debugging

### ISSUE THREAD

**Issue by zcnet4** [WebFreak001/code-debug#96] opened 2017-03-02 03:32 UTC
gdb version: 7.11.1

Not support multithreading debugging

https://code.visualstudio.com/docs/languages/cpp Description Supports multithreading debugging.
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/debugSession.ts also supports multi-threaded debugging

details as following:
In the debug console input thread 2 found that the thread can not be switched.
I look at the code because the variableRequest function in miDebugger.getStackVariables uses the thread command to switch back to the previous thread.

---
threadsRequest(response) {
        response.body = {
            threads: [
                new vscode_debugadapter_1.Thread(this.threadID, "Thread 1"),
		new vscode_debugadapter_1.Thread(this.threadID_xx2, "Thread 2")
            ]
        };
        this.sendResponse(response);
    }

**Comment by WebFreak001** [comment] 2017-03-02 10:23
Duplicate of #36 

If you want it hardcoded for 2 Threads consider temporarily adding it for yourself.

**Closed by WebFreak001** 2017-03-02 10:23 UTC
