### ISSUE TITLE
[Question] Difference from C/C++ debugging

### ISSUE THREAD

**Issue by paradajz** [WebFreak001/code-debug#213] opened 2020-03-06 21:37 UTC
I'm sorry if this has been answered before - if it has I haven't been able to find it, nor did I find this mentioned in documentation anywhere, so here goes:

What is the purpose of this extension? I mean, what's the difference between this and integrated VSCode debugging which comes with C/C++ extension? What does "native" mean in this context? At first I thought this extension talks to GDB directly without MI protocol, but then I saw lldb-mi is required for this as well. I'm obviously missing something here.

I think it would be a good idea to add the answers to what/why questions in documentation.

**Comment by jscsharp** [comment] 2020-03-07 17:38
C/C++ extension from Microsoft uses MIEngine:
https://github.com/microsoft/MIEngine
which is C#  project.
But this extension is all in Typescript and connect to gdb mi.
I think, you can ignore "native" word. Both these projects use  gdb mi.

**Comment by WebFreak001** [comment] 2020-03-09 14:15
duplicate of #187

**Closed by WebFreak001** 2020-03-09 14:15 UTC
