### ISSUE TITLE
No symbol table is loaded.  Use the "file" command.

### ISSUE THREAD

**Issue by bsed** [WebFreak001/code-debug#112] opened 2017-06-19 09:23 UTC
my task.json
```
{
    "version": "0.1.0",
    "command": "cargo",
    "isShellCommand": true,
    "args": ["build"],
    "showOutput": "always"
}
```

lanuch.json
```
{
    "version": "0.2.0",
    "configurations": [{
        "type": "gdb",
        "request": "launch",
        "gdbpath": "D:/msys64/mingw64/bin/gdb.exe",
        "name": "launch",
        "target": "./target/debug/example.exe",
        "cwd": "${workspaceRoot}"

    }]
}
```

how i use gdb  attach param ?

No symbol table is loaded.  Use the "file" command.
Running executable
[New Thread 8824.0x1dc0]
[New Thread 8824.0x3d94]
[New Thread 8824.0x1518]
[New Thread 8824.0x1a64]
Hello, world!
[Thread 8824.0x3d94 exited with code 0]

**Comment by WebFreak001** [comment] 2017-06-19 20:13
Duplicate of #101, try https://github.com/WebFreak001/code-debug/issues/101#issuecomment-296396732 to solve this

**Closed by WebFreak001** 2017-06-19 20:13 UTC
