### ISSUE TITLE
Tabs are blank while debugging

### ISSUE THREAD

**Issue by cmrigney** [WebFreak001/code-debug#84] opened 2016-11-30 19:41 UTC
I'm seeing a very odd issue when I hit a breakpoint where all my tabs become blank.  Any ideas?  Can you duplicate this?

![image](https://cloud.githubusercontent.com/assets/3259448/20768171/e1910a2e-b70a-11e6-9173-d64de096dd49.png)

**Comment by WebFreak001** [comment] 2016-11-30 20:13
Did you modify your vscode or install some extension which modifies the vscode source code? The button next to the restart button doesn't come with vscode so I think it might be some other extension causing this. It is working fine for me.

**Comment by cmrigney** [comment] 2016-11-30 20:47
No I didn't modify it and it normally just shows a stop button for other types of launches.  I'm on VS code version 1.7.2.  I do have the C/C++ extension and the C/C++ Clang extension installed.  Maybe it's detecting remote and doing that?

**Comment by WebFreak001** [comment] 2016-11-30 20:49
Oh right maybe they just replaced the stop button there, thats why it looks so weird. Hm gonna investigate on that issue then.

**Comment by cmrigney** [comment] 2016-11-30 21:06
Thanks!  By the way extremely useful extension!

**Comment by WebFreak001** [comment] 2016-12-31 14:20
Sidenote: the button looks weird because it's attached and not launched. But still couldn't reproduce.

Also this is a problem with vscode and not with the extension because extensions can't really change the UI that much and debugger extension can do that even less, so I am closing this. If you still have that issue report it to the [vscode repository](https://github.com/Microsoft/vscode)

**Closed by WebFreak001** 2016-12-31 14:20 UTC
Labels: bug, cant reproduce
