### ISSUE TITLE
Breakpoints source code mismatch with Visual Code on WSL and remote GDB 

### ISSUE THREAD

**Issue by pzarzycki** [WebFreak001/code-debug#231] opened 2020-07-10 15:54 UTC
Visual Code on WSL

Breakpoint set from the editor window (and appear in Run/Breakpoints).
![image](https://user-images.githubusercontent.com/3589204/87172882-374f7c00-c2d5-11ea-859d-538501d18afc.png)

But when running debug command breakpoint fails to be setup due to **path mismatch**:
`No source file named /mnt/c/Users/User(AD)/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4/~/debug/main.cpp.`
instead of actual file location:
` /mnt/d/PRJ/BasicCppSample/main.cpp`

**Program is being run correctly, but no breakpoints are matched.**

**Local** path to source code (**${workspaceRoot}**):
`/mnt/d/PRJ/BasicCppSample`
Local bin path
`/mnt/d/PRJ/BasicCppSample/build`

Remote path:
`~/debug/`

Testing with gdb (breakpoint was set properly):

```
(gdb) target extended-remote | sshpass -p "pass" ssh -T user@192.181.0.107 gdbserver --multi -
Remote debugging using | sshpass -p "pass" ssh -T user@192.181.0.107 gdbserver --multi -
Remote debugging using stdio
(gdb) set remote exec-file ~/debug/BasicCppSample
(gdb) file BasicCppSample
Reading symbols from BasicCppSample...done.
(gdb) b main
Breakpoint 1 at 0x8a4: file /mnt/d/PRJ/BasicCppSample/main.cpp, line 24.
(gdb) run
Starting program: /mnt/d/PRJ/BasicCppSample/build/BasicCppSample debug/BasicCppSample
stdin/stdout redirected
Process ~/debug/BasicCppSample created; pid = 13755
warning: while parsing target description (at line 1): Target description specified unknown architecture "aarch64"
warning: Could not load XML target description; ignoring
```

Visual Code configuration:
![image](https://user-images.githubusercontent.com/3589204/87173327-dd02eb00-c2d5-11ea-84b3-bee11485d526.png)

Additional information (Debug Console output with **"printCalls": true**):

```
Running gdb over ssh...
1-gdb-set target-async on
2-environment-directory "~/debug"
3-file-exec-and-symbols "~/debug/BasicCppSample"
4-environment-cd "~/debug"
5-break-delete
6-break-insert -f "/mnt/c/Users/User(AD)/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4/~/debug/main.cpp:26"
No source file named /mnt/c/Users/User(AD)/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4/~/debug/main.cpp.
7-thread-info
Running executable
8-exec-run
9-thread-info
Hello world 2!
[Inferior 1 (process 19260) exited normally]
-gdb-exit

```

**Comment by WebFreak001** [comment] 2020-07-10 19:47
duplicate of #167

**Closed by WebFreak001** 2020-07-10 19:47 UTC
