### ISSUE TITLE
Breakpoints are not working in gdb.ts or mibase.ts with extension debugging

### ISSUE THREAD

**Issue by PaDebug** [WebFreak001/code-debug#269] opened 2021-05-18 13:54 UTC
Hey,

currently I try to understand the core-debug extension. Before I started a debug session in the extension development host (attach to gdb server, which is working fine), I enabled some breakpoints in the gdb.ts or mibase.ts to watch some variables, but they don´t get fired during the debug session. Can somebody explain why? Do you have the same behavior?

Thanks in advance.

**Comment by WebFreak001** [comment] 2021-05-18 14:16
debug adapters are unlike regular vscode extensions separate processes, so you will have to attach to the separately launched nodejs instance. So all debugging of the debug adapter has been done using print calls so far. I don't know if vscode added capability for proper debugging here or if it's possible to enable it, but using unittests and debug printlns it was possible to do everything so far.

**Comment by GitMensch** [comment] 2022-04-11 06:24
I've stumbled over this myself and though "I definitely make something wrong, but can't figure out what" so far. Looks like this wasn't the case. I guess https://github.com/Marus/cortex-debug/#how-to-debug applies to this extension too, has anybody tested this?
Notes for this should go to #305, of course.

**Comment by GitMensch** [comment] 2022-05-03 09:34
duplicate of #176, documentation adjusted with 23e0a7a838c487a7b2ec4c51cb75598a8647b0e8

**Closed by GitMensch** 2022-05-03 09:34 UTC
