### ISSUE TITLE
"Cannot read property 'toLowerCase' of undefined" when LLDB missing

### ISSUE THREAD

**Issue by c7hm4r** [WebFreak001/code-debug#103] opened 2017-04-11 21:32 UTC
I got the following exception using LLDB when I started debugging:

```
Cannot read property 'toLowerCase' of undefined

DebugService.updateStateAndEmit (debugService.ts:473)
DebugService.focusStackFrameAndEvaluate (debugService.ts:493)
(anonymous function) (debugService.ts:759)
notifySuccess (winjs.base.raw.js:1170)
enter (winjs.base.raw.js:901)
_run (winjs.base.raw.js:1068)
_error (winjs.base.raw.js:1041)
(anonymous function) (v8Protocol.ts:56)
_cancelAction (winjs.base.raw.js:1652)
enter (winjs.base.raw.js:805)
_run (winjs.base.raw.js:1068)
cancel (winjs.base.raw.js:964)
_cancelAction (winjs.base.raw.js:1311)
enter (winjs.base.raw.js:805)
_run (winjs.base.raw.js:1068)
cancel (winjs.base.raw.js:964)
(anonymous function) (rawDebugSession.ts:296)
(anonymous function) (rawDebugSession.ts:296)
```

The exception message is displayed in the UI on a bar appearing at the top.

VS Code version: tag `1.11.1`, revision d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
NativeDebug version: 0.17.0

launch.json
```
    {
      "name": "LLDB Test",
      "type": "lldb-mi",
      "request": "launch",
      "target": "./target/debug/…",
      "cwd": "${workspaceRoot}",
      "preLaunchTask": "build-test",
      "env": {
        "RUST_BACKTRACE": "1"
      }
    }
```

The `preLaunchTask` succeeds.

If submitting a bug please make sure

The problem could be solved by installing LLDB. It would have saved time if a more helpful message would have been displayed. Maybe the extension could check the presence of LLDB or GDB at the start of the debugging session?

**Comment by WebFreak001** [comment] 2017-04-11 21:35
Duplicate of #102

**Closed by WebFreak001** 2017-04-11 21:35 UTC
