### ISSUE TITLE
Load core file - how to disable `exec-run`?

### ISSUE THREAD

**Issue by infn-ke** [WebFreak001/code-debug#385] opened 2022-11-07 21:03 UTC
Trying to load a core file using a launch task. But how do I disable the `exec-run` step? Or is there another way to load a core file without a launch task?

This [snippet](https://github.com/WebFreak001/code-debug/issues/121#issuecomment-324859504) uses a launch task, but problem is that it will try to execute the target, which will not work well for cross-compiled binaries.

**Comment by GitMensch** [comment] 2022-11-07 21:22
Looks like a duplicate of #360. See the (not again tested) way to not execute the program by overriding the default args or the workaround to just execute `core /path/to/file` when already in an debugging session.

**Closed by GitMensch** 2022-11-07 21:22 UTC

**Comment by infn-ke** [comment] 2022-11-07 21:32
> Looks like a duplicate of #360. See there for a (not again tested) way to not execute the program by overriding the default args or the workaround to just execute `core /path/to/file` when already in an debugging session.

Did not work for me. The plugin still tries to run the executable.

```bash
5-thread-info
6-thread-info
7-thread-info
Running executable
8-exec-run
-gdb-exit
```

**Comment by brownts** [comment] 2022-11-07 21:38
This isn't officially supported, but I'd try using the "attach" configuration, setting `stopAtConnect` to `true` and then adding the appropriate autorun command `target core <filename>`.  Not sure if that will work, but might be worth a try.

**Comment by infn-ke** [comment] 2022-11-08 09:33
Not working either. Seems I cannot inhibit the plugin from trying to invoke `exec-run`.

**Comment by GitMensch** [comment] 2022-11-08 11:58
Just rechecked: only `attach` will get away from  `exec-run` (and for not having it run `exec-continue` you'd also need to specify `stopAtConnect`, see #360 for tested configuration (and yes, that's totally bad, but it works).

**Comment by brownts** [comment] 2022-11-08 13:49
See #360 also for an example of using the "extended-remote" option.
